// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1Valet_web_api.Models;

namespace _1Valet_web_api.Migrations
{
    [DbContext(typeof(DbContextClass))]
    [Migration("20220205210308_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_1Valet_web_api.Models.DeviceTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<Guid?>("TypesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TypesId");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("_1Valet_web_api.Models.Devices", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DeviceTypesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceUsage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypesId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("_1Valet_web_api.Models.Types", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("_1Valet_web_api.Models.DeviceTypes", b =>
                {
                    b.HasOne("_1Valet_web_api.Models.Types", "Types")
                        .WithMany("DeviceTypes")
                        .HasForeignKey("TypesId");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("_1Valet_web_api.Models.Devices", b =>
                {
                    b.HasOne("_1Valet_web_api.Models.DeviceTypes", "DeviceTypes")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypesId");

                    b.Navigation("DeviceTypes");
                });

            modelBuilder.Entity("_1Valet_web_api.Models.DeviceTypes", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("_1Valet_web_api.Models.Types", b =>
                {
                    b.Navigation("DeviceTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
